---
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: podinfo-system
spec:
  interval: 1h
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo-system
spec:
  interval: 50m
  releaseName: podinfo
  targetNamespace: podinfo-system
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      version: 6.8.1
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: podinfo-system
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    replicaCount: 6
