apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: monitoring-system
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring-system
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---

