---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: sealed-secrets-system
spec:
  interval: 1h
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets-system
spec:
  interval: 1h
  releaseName: sealed-secrets-controller
  targetNamespace: sealed-secrets-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: ChartVersion
      version: ">=1.15.0-0"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: sealed-secrets-system
